package dev.canverse.stocks.ledger.domain;

public enum ActivityType {
    OPENING_BALANCE, CASH_DEPOSIT, CASH_WITHDRAWAL, CASH_FEE, CASH_INTEREST_CREDIT, OWNED_TRANSFER, REVERSAL, RECONCILIATION_ADJUSTMENT
}
