package dev.canverse.stocks.ledger.domain;

public enum PostingRole {
    OPENING, DEPOSIT, WITHDRAWAL, FEE, INTEREST_CREDIT, TRANSFER_SOURCE, TRANSFER_DESTINATION, TRADE_PURCHASE, TRADE_PROCEEDS, REVERSAL, ADJUSTMENT
}
