/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/reference/instruments/{instrumentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["updateMetadata"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/opening-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["correctOpening"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transfers/previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations/{reconciliationId}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["correct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activityId}/reversals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/reconciliation-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["markets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/markets/{marketId}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["countries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations/{reconciliationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{familyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InstrumentAliasInput: {
            /** @enum {string} */
            type: "TICKER" | "ISIN" | "PROVIDER" | "USER";
            value: string;
        };
        ManualInstrumentUpdateRequest: {
            /** Format: int64 */
            version?: number;
            name: string;
            /** @enum {string} */
            valuationMethod: "MARKET_OBSERVATION" | "MANUAL_VALUE" | "NOT_VALUED";
            active?: boolean;
            aliases?: components["schemas"]["InstrumentAliasInput"][];
        };
        InstrumentAliasResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "TICKER" | "ISIN" | "PROVIDER" | "USER";
            value: string;
        };
        InstrumentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId?: string;
            /** Format: uuid */
            marketId: string;
            marketCode: string;
            symbol: string;
            name: string;
            /** @enum {string} */
            instrumentType: "EQUITY" | "ETF" | "FUND" | "INDEX" | "BOND" | "CRYPTO" | "COMMODITY" | "CURRENCY" | "CASH_EQUIVALENT" | "OTHER";
            quotationCurrency: string;
            /** @enum {string} */
            valuationMethod: "MARKET_OBSERVATION" | "MANUAL_VALUE" | "NOT_VALUED";
            active?: boolean;
            sourceKind: string;
            /** Format: int64 */
            version?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            aliases: components["schemas"]["InstrumentAliasResponse"][];
        };
        AccountMetadataRequest: {
            /** Format: uuid */
            clientRequestId: string;
            name: string;
            timeZone: string;
            /** Format: int64 */
            version: number;
        };
        FinancialAccountResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "CASH_CURRENT" | "CASH_SAVINGS" | "CASH_WALLET" | "BROKERAGE" | "CREDIT_CARD" | "LOAN";
            /** @enum {string} */
            trackingMode: "FULL_LEDGER" | "HOLDINGS_ONLY";
            currency: string;
            timeZone: string;
            /** @enum {string} */
            policy?: "HARD_FLOOR" | "SOFT_FLOOR" | "TRACK_REALITY" | "AUTHORIZED_LIMIT";
            authorizedLimit?: string;
            archived?: boolean;
            /** Format: date-time */
            archivedAt?: string;
            /** @enum {string} */
            cashCoverageStatus: "KNOWN_FROM_OPENING" | "UNTRACKED";
            /** Format: date-time */
            coverageFrom?: string;
            sourceKind: string;
            /** Format: int64 */
            version?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            policyBreach?: boolean;
        };
        AccountPolicyRequest: {
            /** Format: uuid */
            clientRequestId: string;
            /** @enum {string} */
            policy?: "HARD_FLOOR" | "SOFT_FLOOR" | "TRACK_REALITY" | "AUTHORIZED_LIMIT";
            authorizedLimit?: string;
            /** Format: int64 */
            version: number;
        };
        OpeningCorrectionRequest: {
            /** Format: uuid */
            clientRequestId: string;
            amount: string;
            /** Format: date-time */
            effectiveAt: string;
            correctionReason: string;
            /** Format: int64 */
            version: number;
        };
        TransferRequest: {
            /** Format: uuid */
            clientRequestId: string;
            /** Format: uuid */
            sourceAccountId: string;
            /** Format: uuid */
            destinationAccountId: string;
            amount: string;
            /** @enum {string} */
            recordingMode: "CURRENT_ACTION" | "HISTORICAL_FACT";
            /** Format: date-time */
            effectiveAt: string;
            confirmPolicyBreach?: boolean;
            /** Format: int64 */
            expectedSourceBalanceVersion?: number;
            /** Format: int64 */
            expectedDestinationBalanceVersion?: number;
        };
        ActivityResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            activityType: "OPENING_BALANCE" | "CASH_DEPOSIT" | "CASH_WITHDRAWAL" | "CASH_FEE" | "CASH_INTEREST_CREDIT" | "OWNED_TRANSFER" | "REVERSAL" | "RECONCILIATION_ADJUSTMENT";
            /** @enum {string} */
            recordingMode: "CURRENT_ACTION" | "HISTORICAL_FACT";
            /** Format: date-time */
            effectiveAt: string;
            /** Format: date-time */
            recordedAt: string;
            /** @enum {string} */
            policyDecision: "NOT_APPLICABLE" | "ALLOWED" | "CONFIRMED_BREACH" | "HISTORICAL_BREACH_RECORDED";
            sourceKind: string;
            /** Format: uuid */
            reversesActivityId?: string;
            /** Format: uuid */
            supersedesActivityId?: string;
            postings: components["schemas"]["PostingResponse"][];
        };
        PostingResponse: {
            /** Format: uuid */
            accountId: string;
            /** Format: uuid */
            pocketId: string;
            currency: string;
            amount: string;
            /** @enum {string} */
            role: "OPENING" | "DEPOSIT" | "WITHDRAWAL" | "FEE" | "INTEREST_CREDIT" | "TRANSFER_SOURCE" | "TRANSFER_DESTINATION" | "REVERSAL" | "ADJUSTMENT";
        };
        TransferPreviewRequest: {
            /** Format: uuid */
            sourceAccountId: string;
            /** Format: uuid */
            destinationAccountId: string;
            amount: string;
            /** @enum {string} */
            recordingMode: "CURRENT_ACTION" | "HISTORICAL_FACT";
            /** Format: date-time */
            effectiveAt: string;
            confirmPolicyBreach?: boolean;
        };
        TransferPreviewResponse: {
            /** Format: uuid */
            sourceAccountId: string;
            /** Format: uuid */
            destinationAccountId: string;
            currency: string;
            amount: string;
            sourceBefore: string;
            sourceAfter: string;
            destinationBefore: string;
            destinationAfter: string;
            /** @enum {string} */
            sourceDecision: "NOT_APPLICABLE" | "ALLOWED" | "CONFIRMED_BREACH" | "HISTORICAL_BREACH_RECORDED";
            /** @enum {string} */
            destinationDecision: "NOT_APPLICABLE" | "ALLOWED" | "CONFIRMED_BREACH" | "HISTORICAL_BREACH_RECORDED";
            /** Format: int64 */
            sourceVersion?: number;
            /** Format: int64 */
            destinationVersion?: number;
            allowed?: boolean;
        };
        ManualInstrumentCreateRequest: {
            /** Format: uuid */
            marketId: string;
            symbol: string;
            name: string;
            /** @enum {string} */
            instrumentType: "EQUITY" | "ETF" | "FUND" | "INDEX" | "BOND" | "CRYPTO" | "COMMODITY" | "CURRENCY" | "CASH_EQUIVALENT" | "OTHER";
            quotationCurrency: string;
            /** @enum {string} */
            valuationMethod: "MARKET_OBSERVATION" | "MANUAL_VALUE" | "NOT_VALUED";
            aliases?: components["schemas"]["InstrumentAliasInput"][];
        };
        ReconciliationCorrectionRequest: {
            statementReference: string;
            /** Format: date-time */
            statementOpeningAt: string;
            /** Format: date-time */
            statementClosingAt: string;
            statementOpeningBalance: string;
            statementClosingBalance: string;
            /** Format: uuid */
            clientRequestId: string;
            /** Format: int64 */
            expectedBalanceVersion: number;
            /** @enum {string} */
            resolution: "CONFIRM_BALANCED" | "CREATE_ADJUSTMENT";
            adjustmentReason?: string;
            correctionReason: string;
        };
        ReconciliationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            /** Format: uuid */
            cashPocketId: string;
            currency: string;
            statementReference: string;
            /** Format: date-time */
            statementOpeningAt: string;
            /** Format: date-time */
            statementClosingAt: string;
            statementOpeningBalance: string;
            statementClosingBalance: string;
            ledgerOpeningBalance: string;
            ledgerClosingBalanceBeforeAdjustment: string;
            openingDifference: string;
            periodNetPostedAmount: string;
            closingDifference: string;
            adjustmentAmount?: string;
            /** Format: int64 */
            periodPostingCount?: number;
            /** Format: int64 */
            totalPostingCountThroughClosing?: number;
            /** @enum {string} */
            resolution: "BALANCED" | "ADJUSTED";
            /** Format: uuid */
            adjustmentActivityId?: string;
            adjustmentReason?: string;
            /** Format: uuid */
            supersedesReconciliationId?: string;
            /** @enum {string} */
            lifecycleStatus: "CURRENT" | "STALE" | "SUPERSEDED";
            sourceKind: string;
            /** Format: date-time */
            createdAt: string;
        };
        RegistrationRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegistrationResponse: {
            /** Format: uuid */
            userId: string;
        };
        LocalRefreshRequest: {
            refreshToken?: string;
            /** @enum {string} */
            refreshTokenDelivery: "RESPONSE_BODY" | "HTTP_ONLY_COOKIE";
        };
        LocalAuthenticationResponse: {
            /** Format: uuid */
            sessionId: string;
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            /** Format: date-time */
            serverTime: string;
            refreshToken?: string;
        };
        LogoutRequest: {
            /** @enum {string} */
            scope: "CURRENT_SESSION" | "ALL_SESSIONS";
        };
        LocalLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            deviceLabel?: string;
            /** @enum {string} */
            refreshTokenDelivery: "RESPONSE_BODY" | "HTTP_ONLY_COOKIE";
        };
        ReversalRequest: {
            /** Format: uuid */
            clientRequestId: string;
            correctionReason: string;
        };
        CreateFinancialAccountRequest: {
            /** Format: uuid */
            clientRequestId: string;
            name: string;
            /** @enum {string} */
            kind: "CASH_CURRENT" | "CASH_SAVINGS" | "CASH_WALLET" | "BROKERAGE" | "CREDIT_CARD" | "LOAN";
            /** @enum {string} */
            trackingMode: "FULL_LEDGER" | "HOLDINGS_ONLY";
            currency: string;
            timeZone: string;
            /** @enum {string} */
            policy?: "HARD_FLOOR" | "SOFT_FLOOR" | "TRACK_REALITY" | "AUTHORIZED_LIMIT";
            authorizedLimit?: string;
            openingState?: components["schemas"]["OpeningStateRequest"];
        };
        OpeningStateRequest: {
            amount: string;
            /** Format: date-time */
            effectiveAt: string;
        };
        ReconciliationCommitRequest: {
            statementReference: string;
            /** Format: date-time */
            statementOpeningAt: string;
            /** Format: date-time */
            statementClosingAt: string;
            statementOpeningBalance: string;
            statementClosingBalance: string;
            /** Format: uuid */
            clientRequestId: string;
            /** Format: int64 */
            expectedBalanceVersion: number;
            /** @enum {string} */
            resolution: "CONFIRM_BALANCED" | "CREATE_ADJUSTMENT";
            adjustmentReason?: string;
        };
        ReconciliationPreviewRequest: {
            statementReference: string;
            /** Format: date-time */
            statementOpeningAt: string;
            /** Format: date-time */
            statementClosingAt: string;
            statementOpeningBalance: string;
            statementClosingBalance: string;
        };
        ReconciliationPreviewResponse: {
            /** Format: uuid */
            accountId: string;
            /** Format: uuid */
            cashPocketId: string;
            currency: string;
            /** @enum {string} */
            coverageStatus: "KNOWN_FROM_OPENING" | "UNTRACKED";
            /** Format: date-time */
            coverageFrom: string;
            statementReference: string;
            /** Format: date-time */
            statementOpeningAt: string;
            /** Format: date-time */
            statementClosingAt: string;
            statementOpeningBalance: string;
            statementClosingBalance: string;
            ledgerOpeningBalance: string;
            ledgerClosingBalanceBeforeAdjustment: string;
            openingDifference: string;
            periodNetPostedAmount: string;
            closingDifference: string;
            /** Format: int64 */
            periodPostingCount?: number;
            /** Format: int64 */
            totalPostingCountThroughClosing?: number;
            /** Format: int64 */
            projectionVersion?: number;
            admissibleResolutions: string[];
            warnings: string[];
        };
        ArchiveAccountRequest: {
            /** Format: uuid */
            clientRequestId: string;
            /** Format: int64 */
            version: number;
        };
        CashActivityRequest: {
            /** Format: uuid */
            clientRequestId: string;
            /** @enum {string} */
            activityType: "CASH_DEPOSIT" | "CASH_WITHDRAWAL" | "CASH_FEE" | "CASH_INTEREST_CREDIT";
            amount: string;
            /** @enum {string} */
            recordingMode: "CURRENT_ACTION" | "HISTORICAL_FACT";
            /** Format: date-time */
            effectiveAt: string;
            confirmPolicyBreach?: boolean;
            /** Format: int64 */
            expectedBalanceVersion?: number;
        };
        MarketResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            marketType: string;
            countryCode?: string;
            timeZone: string;
            quotationCurrencies: string[];
            primaryQuotationCurrency?: string;
            active?: boolean;
            sourceKind: string;
        };
        MarketCalendarResponse: {
            /** Format: uuid */
            marketId: string;
            marketCode: string;
            timeZone: string;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** @enum {string} */
            coverageStatus: "NONE" | "PARTIAL" | "COMPLETE";
            sessions: components["schemas"]["MarketCalendarSessionResponse"][];
            missingDates: string[];
        };
        MarketCalendarSessionResponse: {
            /** Format: date */
            date: string;
            /** @enum {string} */
            sessionStatus: "OPEN" | "CLOSED";
            opensAt?: string;
            closesAt?: string;
            sourceKind: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        InstrumentSummaryResponse: {
            /** Format: uuid */
            id: string;
            symbol: string;
            name: string;
            /** @enum {string} */
            instrumentType: "EQUITY" | "ETF" | "FUND" | "INDEX" | "BOND" | "CRYPTO" | "COMMODITY" | "CURRENCY" | "CASH_EQUIVALENT" | "OTHER";
            /** Format: uuid */
            marketId: string;
            marketCode: string;
            quotationCurrency: string;
            /** @enum {string} */
            valuationMethod: "MARKET_OBSERVATION" | "MANUAL_VALUE" | "NOT_VALUED";
            active?: boolean;
            sourceKind: string;
            ownerManaged?: boolean;
            aliases: components["schemas"]["InstrumentAliasResponse"][];
        };
        SliceResponseInstrumentSummaryResponse: {
            items: components["schemas"]["InstrumentSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            hasNext: boolean;
        };
        CurrencyResponse: {
            code: string;
            name: string;
            symbol: string;
            /** Format: int32 */
            minorUnit?: number;
            active?: boolean;
        };
        CountryResponse: {
            code: string;
            name: string;
            active?: boolean;
        };
        CurrentUserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        DeviceSessionResponse: {
            /** Format: uuid */
            familyId: string;
            /** Format: uuid */
            latestGenerationId: string;
            deviceLabel?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt?: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            endedAt?: string;
            /** @enum {string} */
            status: "ACTIVE" | "EXPIRED" | "REVOKED" | "COMPROMISED";
            current?: boolean;
        };
        SliceResponseActivityResponse: {
            items: components["schemas"]["ActivityResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            hasNext: boolean;
        };
        SliceResponseReconciliationResponse: {
            items: components["schemas"]["ReconciliationResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            hasNext: boolean;
        };
        BalanceResponse: {
            /** Format: uuid */
            accountId: string;
            /** Format: date-time */
            requestedAsOf: string;
            /** Format: date-time */
            actualAsOf: string;
            nativeCurrency: string;
            /** @enum {string} */
            coverageStatus: "KNOWN_FROM_OPENING" | "UNTRACKED";
            /** Format: date-time */
            coverageFrom?: string;
            sourceKind: string;
            /** @enum {string} */
            projectionStatus: "NOT_APPLICABLE" | "CURRENT" | "STALE" | "REBUILDING" | "FAILED";
            /** Format: date-time */
            watermarkRecordedAt?: string;
            /** Format: uuid */
            watermarkActivityId?: string;
            ledgerBalance?: string;
            clearedBalance?: string;
            cashHeld?: string;
            liabilityOutstanding?: string;
            overdraftUsed?: string;
            creditAvailable?: string;
            policyBreach?: boolean;
            lastReconciliation?: components["schemas"]["LastReconciliationSummaryResponse"];
        };
        LastReconciliationSummaryResponse: {
            /** Format: uuid */
            reconciliationId: string;
            /** Format: date-time */
            statementClosingAt: string;
            statementClosingBalance: string;
            /** @enum {string} */
            resolution: "BALANCED" | "ADJUSTED";
            /** @enum {string} */
            lifecycleStatus: "CURRENT" | "STALE" | "SUPERSEDED";
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrumentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstrumentResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrumentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualInstrumentUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstrumentResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FinancialAccountResponse"];
                };
            };
        };
    };
    updateMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountMetadataRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FinancialAccountResponse"];
                };
            };
        };
    };
    updatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountPolicyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FinancialAccountResponse"];
                };
            };
        };
    };
    correctOpening: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpeningCorrectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FinancialAccountResponse"];
                };
            };
        };
    };
    transfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferPreviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransferPreviewResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                query?: string;
                marketId?: string;
                type?: "EQUITY" | "ETF" | "FUND" | "INDEX" | "BOND" | "CRYPTO" | "COMMODITY" | "CURRENCY" | "CASH_EQUIVALENT" | "OTHER";
                includeInactive?: boolean;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SliceResponseInstrumentSummaryResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualInstrumentCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstrumentResponse"];
                };
            };
        };
    };
    correct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reconciliationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconciliationCorrectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReconciliationResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegistrationResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalRefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocalAuthenticationResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocalAuthenticationResponse"];
                };
            };
        };
    };
    reverse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReversalRequest"];
            };
        };
        responses: {
            /** @description Activity reversal created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FinancialAccountResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFinancialAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FinancialAccountResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SliceResponseReconciliationResponse"];
                };
            };
        };
    };
    commit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconciliationCommitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReconciliationResponse"];
                };
            };
        };
    };
    preview_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconciliationPreviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReconciliationPreviewResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FinancialAccountResponse"];
                };
            };
        };
    };
    record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashActivityRequest"];
            };
        };
        responses: {
            /** @description Cash activity created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityResponse"];
                };
            };
        };
    };
    markets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarketResponse"][];
                };
            };
        };
    };
    calendar: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                marketId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarketCalendarResponse"];
                };
            };
        };
    };
    currencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrencyResponse"][];
                };
            };
        };
    };
    countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CountryResponse"][];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reconciliationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReconciliationResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeviceSessionResponse"][];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                familyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeviceSessionResponse"];
                };
            };
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                familyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_2: {
        parameters: {
            query: {
                accountId?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SliceResponseActivityResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityResponse"];
                };
            };
        };
    };
    balance: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BalanceResponse"];
                };
            };
        };
    };
}
