ALTER TABLE instrument.instrument_snapshots
    ADD COLUMN id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN currency_code VARCHAR(3);

UPDATE instrument.instrument_snapshots s
SET currency_code = i.denomination_currency
FROM instrument.instruments i
WHERE s.instrument_id = i.id;

ALTER TABLE instrument.instrument_snapshots
    ALTER COLUMN currency_code SET NOT NULL,
    DROP CONSTRAINT instrument_snapshots_pkey,
    ADD CONSTRAINT instrument_snapshots_pkey PRIMARY KEY (id),
    ADD CONSTRAINT uq_instrument_currency UNIQUE (instrument_id, currency_code);

ALTER TABLE instrument.instruments
    DROP COLUMN denomination_currency;

SELECT setval(pg_get_serial_sequence('instrument.instrument_snapshots', 'id'), coalesce(max(id), 0) + 1, false)
FROM instrument.instrument_snapshots;

ALTER TABLE portfolio.positions
    ADD COLUMN currency_code VARCHAR(3) NOT NULL DEFAULT 'TRY';

CREATE TABLE instrument.market_currencies
(
    market_id     BIGINT REFERENCES instrument.markets (id),
    currency_code VARCHAR(3) NOT NULL,
    PRIMARY KEY (market_id, currency_code)
);