ALTER TABLE holdings
    DROP COLUMN IF EXISTS total_tax;

ALTER TABLE holding_history
    DROP COLUMN IF EXISTS total_tax;

CREATE TABLE portfolios
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_portfolios PRIMARY KEY (id),
    CONSTRAINT fk_portfolios_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_portfolios_user_id ON portfolios (user_id);

-- Insert default portfolio for each user based on existing holdings
INSERT INTO portfolios (name, user_id, created_at, updated_at)
SELECT DISTINCT 'My Portfolio', user_id, NOW(), NOW()
FROM holdings;

-- Add portfolio_id to holdings table and set up foreign key constraint
ALTER TABLE holdings
    ADD COLUMN portfolio_id BIGINT,
    ADD CONSTRAINT FK_HOLDINGS_ON_PORTFOLIO FOREIGN KEY (portfolio_id) REFERENCES portfolios (id);

-- Add index on portfolio_id for faster lookups
CREATE INDEX idx_holdings_portfolio_id ON holdings (portfolio_id);

-- Update holdings table to reference portfolios instead of users
UPDATE holdings
SET portfolio_id = (SELECT id FROM portfolios WHERE user_id = holdings.user_id);

-- Remove user_id from holdings table and update portfolio_id to not null
ALTER TABLE holdings
    DROP COLUMN user_id,
    ALTER COLUMN portfolio_id SET NOT NULL;
