CREATE TABLE currencies
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                     VARCHAR(10)                             NOT NULL,
    name                     VARCHAR(255)                            NOT NULL,
    symbol                   VARCHAR(10)                             NOT NULL,
    decimals                 INTEGER                                 NOT NULL,
    exchange_rate            DECIMAL(38, 18)                         NOT NULL,
    exchange_rate_updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_active                BOOLEAN                                 NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_currencies PRIMARY KEY (id)
);

ALTER TABLE currencies
    ADD CONSTRAINT uc_currencies_code UNIQUE (code);

INSERT INTO currencies (code, name, symbol, decimals, exchange_rate, exchange_rate_updated_at, is_active, created_at,
                        updated_at)
VALUES ('USD', 'US Dollar', '$', 2, 1, current_timestamp, true, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('EUR', 'Euro', '€', 2, 0.86, current_timestamp, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('GBP', 'British Pound', '£', 2, 0.79, current_timestamp, true, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('JPY', 'Japanese Yen', '¥', 0, 149.5, current_timestamp, true, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('AUD', 'Australian Dollar', 'A$', 2, 1.52, current_timestamp, true, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('CNY', 'Chinese Yuan', '¥', 2, 7.24, current_timestamp, true, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('RUB', 'Russian Ruble', '₽', 2, 75, current_timestamp, true, CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('TRY', 'Turkish Lira', '₺', 2, 40.65, current_timestamp, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);