CREATE SCHEMA IF NOT EXISTS instrument;

CREATE TYPE instrument_type AS ENUM (
    'STOCK',
    'CRYPTOCURRENCY',
    'CURRENCY_PAIR',
    'COMMODITY',
    'INDEX'
    );

CREATE TYPE market_type AS ENUM (
    'STOCK_EXCHANGE',
    'CRYPTOCURRENCY',
    'FOREX',
    'COMMODITY',
    'INDEX'
    );

CREATE TABLE instrument.markets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    code       VARCHAR(255)                            NOT NULL,
    type       market_type                             NOT NULL,
    country_id BIGINT,
    timezone   VARCHAR(255)                            NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_markets PRIMARY KEY (id),
    CONSTRAINT uc_markets_name UNIQUE (name),
    CONSTRAINT fk_markets_on_country FOREIGN KEY (country_id) REFERENCES countries (id)
);

INSERT INTO instrument.markets (name, code, type, country_id, timezone, is_active, created_at, updated_at)
VALUES ('New York Stock Exchange', 'NYSE', 'STOCK_EXCHANGE', (SELECT id FROM countries c where c.iso_code = 'US'),
        'America/New_York', TRUE, NOW(), NOW()),
       ('NASDAQ', 'NASDAQ', 'STOCK_EXCHANGE', (SELECT id FROM countries c where c.iso_code = 'US'), 'America/New_York',
        TRUE, NOW(), NOW()),
       ('Borsa Istanbul', 'BIST', 'STOCK_EXCHANGE', (SELECT id FROM countries c where c.iso_code = 'TR'),
        'Europe/Istanbul', TRUE, NOW(), NOW());

CREATE TABLE instrument.instruments
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255)                            NOT NULL,
    symbol                VARCHAR(255)                            NOT NULL,
    type                  instrument_type                         NOT NULL,
    denomination_currency VARCHAR(3)                              NOT NULL,
    market_id             BIGINT                                  NOT NULL,
    is_active             BOOLEAN                                 NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_instruments PRIMARY KEY (id),
    CONSTRAINT uc_instruments_symbol UNIQUE (symbol, market_id),
    CONSTRAINT fk_instruments_on_market FOREIGN KEY (market_id) REFERENCES instrument.markets (id)
);

CREATE INDEX idx_instruments_symbol ON instrument.instruments (symbol);
CREATE INDEX idx_instruments_type ON instrument.instruments (type);
CREATE INDEX idx_instruments_market ON instrument.instruments (market_id);

CREATE TABLE instrument.instrument_snapshots
(
    instrument_id        BIGINT                      NOT NULL,
    last                 DECIMAL(38, 18)             NOT NULL,
    previous_close       DECIMAL(38, 18),
    daily_change         DECIMAL(38, 18),
    daily_change_percent DECIMAL(38, 18),
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_instrument_snapshots PRIMARY KEY (instrument_id),
    CONSTRAINT fk_instrument_snapshots_on_instrument FOREIGN KEY (instrument_id) REFERENCES instrument.instruments (id)
);

CREATE TABLE instrument.stock_instruments
(
    instrument_id BIGINT NOT NULL,
    isin          VARCHAR(12),
    CONSTRAINT pk_stock_instruments PRIMARY KEY (instrument_id),
    CONSTRAINT fk_stock_instruments_on_instrument FOREIGN KEY (instrument_id) REFERENCES instrument.instruments (id)
);


INSERT INTO instrument.instruments (name, symbol, type, denomination_currency, market_id, is_active, created_at,
                                    updated_at)
SELECT s.name,
       s.symbol,
       'STOCK',
       'TRY',
       3,
       true,
       now(),
       now()
FROM stocks s;

INSERT INTO instrument.stock_instruments (instrument_id, isin)
SELECT s.id, null
FROM instrument.instruments s;
