ALTER TABLE account.users
    ADD COLUMN last_login_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    ADD COLUMN created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    ADD COLUMN updated_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL;


CREATE TABLE portfolio.dashboards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    currency_id BIGINT                                  NOT NULL,
    is_default  BOOLEAN                                 NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_dashboards PRIMARY KEY (id),
    CONSTRAINT FK_DASHBOARDS_ON_CURRENCY FOREIGN KEY (currency_id) REFERENCES currencies (id),
    CONSTRAINT FK_DASHBOARDS_ON_USER FOREIGN KEY (user_id) REFERENCES account.users (id)
);

CREATE UNIQUE INDEX ux_dashboards_user_id_is_default_true
    ON portfolio.dashboards (user_id)
    WHERE is_default = true;

CREATE TABLE portfolio.dashboard_portfolios
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dashboard_id BIGINT                                  NOT NULL,
    portfolio_id BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_dashboard_portfolios PRIMARY KEY (id),
    CONSTRAINT FK_DASHBOARD_PORTFOLIOS_ON_DASHBOARD FOREIGN KEY (dashboard_id) REFERENCES portfolio.dashboards (id),
    CONSTRAINT FK_DASHBOARD_PORTFOLIOS_ON_PORTFOLIO FOREIGN KEY (portfolio_id) REFERENCES portfolio.portfolios (id),
    CONSTRAINT ux_dashboard_portfolios_on_dashboard_id_and_portfolio_id UNIQUE (dashboard_id, portfolio_id)
);

INSERT INTO portfolio.dashboards (name, currency_id, is_default, user_id, created_at, updated_at)
SELECT 'Dashboard', (SELECT c.id FROM public.currencies c where c.code = 'TRY'), true, u.id, now(), now()
FROM account.users u;

INSERT INTO portfolio.dashboard_portfolios (dashboard_id, portfolio_id, created_at)
SELECT d.id, p.id, now()
FROM portfolio.dashboards d
         JOIN portfolio.portfolios p ON p.user_id = d.user_id
WHERE d.is_default = true;
