package dev.canverse.stocks.investing.domain;

public enum TradeImportIssueCode {
    RECORD_SHAPE_INVALID, EXTERNAL_ID_INVALID, SIDE_INVALID, INSTRUMENT_ID_INVALID, INSTRUMENT_UNSUPPORTED, CURRENCY_INVALID, CURRENCY_MISMATCH,
    EFFECTIVE_AT_INVALID, ECONOMIC_SEQUENCE_INVALID, QUANTITY_INVALID, UNIT_PRICE_INVALID, COMMISSION_INVALID, SETTLED_PRECISION_INVALID,
    SELL_PROCEEDS_NOT_POSITIVE, DUPLICATE_EXTERNAL_ID, DUPLICATE_ROW_IN_FILE, ECONOMIC_ORDER_CONFLICT_IN_FILE
}
