/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedMemberRouteRouteImport } from './routes/_authenticated/_member/route'
import { Route as AuthenticatedMemberDashboardRouteImport } from './routes/_authenticated/_member/dashboard'
import { Route as AuthenticatedMemberTradesRouteRouteImport } from './routes/_authenticated/_member/trades/route'
import { Route as AuthenticatedMemberPortfoliosPortfolioIdRouteImport } from './routes/_authenticated/_member/portfolios/$portfolioId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMemberRouteRoute =
  AuthenticatedMemberRouteRouteImport.update({
    id: '/_member',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemberDashboardRoute =
  AuthenticatedMemberDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedMemberTradesRouteRoute =
  AuthenticatedMemberTradesRouteRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)
const AuthenticatedMemberPortfoliosPortfolioIdRoute =
  AuthenticatedMemberPortfoliosPortfolioIdRouteImport.update({
    id: '/portfolios/$portfolioId',
    path: '/portfolios/$portfolioId',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/trades': typeof AuthenticatedMemberTradesRouteRoute
  '/dashboard': typeof AuthenticatedMemberDashboardRoute
  '/portfolios/$portfolioId': typeof AuthenticatedMemberPortfoliosPortfolioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/trades': typeof AuthenticatedMemberTradesRouteRoute
  '/dashboard': typeof AuthenticatedMemberDashboardRoute
  '/portfolios/$portfolioId': typeof AuthenticatedMemberPortfoliosPortfolioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_authenticated/_member/trades': typeof AuthenticatedMemberTradesRouteRoute
  '/_authenticated/_member/dashboard': typeof AuthenticatedMemberDashboardRoute
  '/_authenticated/_member/portfolios/$portfolioId': typeof AuthenticatedMemberPortfoliosPortfolioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/trades'
    | '/dashboard'
    | '/portfolios/$portfolioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/trades'
    | '/dashboard'
    | '/portfolios/$portfolioId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_member'
    | '/login/'
    | '/register/'
    | '/_authenticated/_member/trades'
    | '/_authenticated/_member/dashboard'
    | '/_authenticated/_member/portfolios/$portfolioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_member': {
      id: '/_authenticated/_member'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedMemberRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_member/dashboard': {
      id: '/_authenticated/_member/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedMemberDashboardRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/_member/trades': {
      id: '/_authenticated/_member/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedMemberTradesRouteRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
    '/_authenticated/_member/portfolios/$portfolioId': {
      id: '/_authenticated/_member/portfolios/$portfolioId'
      path: '/portfolios/$portfolioId'
      fullPath: '/portfolios/$portfolioId'
      preLoaderRoute: typeof AuthenticatedMemberPortfoliosPortfolioIdRouteImport
      parentRoute: typeof AuthenticatedMemberRouteRoute
    }
  }
}

interface AuthenticatedMemberRouteRouteChildren {
  AuthenticatedMemberTradesRouteRoute: typeof AuthenticatedMemberTradesRouteRoute
  AuthenticatedMemberDashboardRoute: typeof AuthenticatedMemberDashboardRoute
  AuthenticatedMemberPortfoliosPortfolioIdRoute: typeof AuthenticatedMemberPortfoliosPortfolioIdRoute
}

const AuthenticatedMemberRouteRouteChildren: AuthenticatedMemberRouteRouteChildren =
  {
    AuthenticatedMemberTradesRouteRoute: AuthenticatedMemberTradesRouteRoute,
    AuthenticatedMemberDashboardRoute: AuthenticatedMemberDashboardRoute,
    AuthenticatedMemberPortfoliosPortfolioIdRoute:
      AuthenticatedMemberPortfoliosPortfolioIdRoute,
  }

const AuthenticatedMemberRouteRouteWithChildren =
  AuthenticatedMemberRouteRoute._addFileChildren(
    AuthenticatedMemberRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMemberRouteRoute: typeof AuthenticatedMemberRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMemberRouteRoute: AuthenticatedMemberRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
