/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AuthenticatedMemberRouteImport } from './routes/_authenticated/_member/route'
import { Route as AuthenticatedMemberPortfolioImport } from './routes/_authenticated/_member/portfolio'

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedMemberRouteRoute = AuthenticatedMemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedMemberPortfolioRoute =
  AuthenticatedMemberPortfolioImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedMemberRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_member': {
      id: '/_authenticated/_member'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedMemberRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_member/portfolio': {
      id: '/_authenticated/_member/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedMemberPortfolioImport
      parentRoute: typeof AuthenticatedMemberRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedMemberRouteRouteChildren {
  AuthenticatedMemberPortfolioRoute: typeof AuthenticatedMemberPortfolioRoute
}

const AuthenticatedMemberRouteRouteChildren: AuthenticatedMemberRouteRouteChildren =
  {
    AuthenticatedMemberPortfolioRoute: AuthenticatedMemberPortfolioRoute,
  }

const AuthenticatedMemberRouteRouteWithChildren =
  AuthenticatedMemberRouteRoute._addFileChildren(
    AuthenticatedMemberRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMemberRouteRoute: typeof AuthenticatedMemberRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMemberRouteRoute: AuthenticatedMemberRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedMemberRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/portfolio': typeof AuthenticatedMemberPortfolioRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedMemberRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/portfolio': typeof AuthenticatedMemberPortfolioRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_member': typeof AuthenticatedMemberRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/_member/portfolio': typeof AuthenticatedMemberPortfolioRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_member'
    | '/login/'
    | '/_authenticated/_member/portfolio'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/_member"
      ]
    },
    "/_authenticated/_member": {
      "filePath": "_authenticated/_member/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_member/portfolio"
      ]
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_authenticated/_member/portfolio": {
      "filePath": "_authenticated/_member/portfolio.tsx",
      "parent": "/_authenticated/_member"
    }
  }
}
ROUTE_MANIFEST_END */
