INSERT INTO exchanges (name, code, country_id, timezone, created_at)
VALUES ('New York Stock Exchange', 'NYSE', (SELECT id FROM public.countries WHERE iso_code = 'US'), 'America/New_York',
        NOW()),
       ('NASDAQ', 'NASDAQ', (SELECT id FROM public.countries WHERE iso_code = 'US'), 'America/New_York', NOW()),
       ('London Stock Exchange', 'LSE', (SELECT id FROM public.countries WHERE iso_code = 'GB'), 'Europe/London',
        NOW()),
       ('Tokyo Stock Exchange', 'TSE', (SELECT id FROM public.countries WHERE iso_code = 'JP'), 'Asia/Tokyo', NOW()),
       ('Shanghai Stock Exchange', 'SSE', (SELECT id FROM public.countries WHERE iso_code = 'CN'), 'Asia/Shanghai',
        NOW()),
       ('Hong Kong Stock Exchange', 'HKEX', (SELECT id FROM public.countries WHERE iso_code = 'CN'), 'Asia/Hong_Kong',
        NOW()),
       ('Euronext', 'EURONEXT', (SELECT id FROM public.countries WHERE iso_code = 'FR'), 'Europe/Paris', NOW()),
       ('Toronto Stock Exchange', 'TSX', (SELECT id FROM public.countries WHERE iso_code = 'CA'), 'America/Toronto',
        NOW()),
       ('Frankfurt Stock Exchange', 'FWB', (SELECT id FROM public.countries WHERE iso_code = 'DE'), 'Europe/Berlin',
        NOW()),
       ('Australian Securities Exchange', 'ASX', (SELECT id FROM public.countries WHERE iso_code = 'AU'),
        'Australia/Sydney',
        NOW()),
       ('Bombay Stock Exchange', 'BSE', (SELECT id FROM public.countries WHERE iso_code = 'IN'), 'Asia/Kolkata', NOW()),
       ('National Stock Exchange of India', 'NSE', (SELECT id FROM public.countries WHERE iso_code = 'IN'),
        'Asia/Kolkata',
        NOW()),
       ('Johannesburg Stock Exchange', 'JSE', (SELECT id FROM public.countries WHERE iso_code = 'ZA'),
        'Africa/Johannesburg',
        NOW()),
       ('SIX Swiss Exchange', 'SIX', (SELECT id FROM public.countries WHERE iso_code = 'CH'), 'Europe/Zurich', NOW()),
       ('Korea Exchange', 'KRX', (SELECT id FROM public.countries WHERE iso_code = 'KR'), 'Asia/Seoul', NOW()),
       ('Saudi Stock Exchange (Tadawul)', 'Tadawul', (SELECT id FROM public.countries WHERE iso_code = 'SA'),
        'Asia/Riyadh',
        NOW()),
       ('Moscow Exchange', 'MOEX', (SELECT id FROM public.countries WHERE iso_code = 'RU'), 'Europe/Moscow', NOW()),
       ('Singapore Exchange', 'SGX', (SELECT id FROM public.countries WHERE iso_code = 'SG'), 'Asia/Singapore', NOW()),
       ('Taiwan Stock Exchange', 'TWSE', (SELECT id FROM public.countries WHERE iso_code = 'TW'), 'Asia/Taipei', NOW()),
       ('BM&FBOVESPA (B3)', 'B3', (SELECT id FROM public.countries WHERE iso_code = 'BR'), 'America/Sao_Paulo', NOW()),
       ('Mexican Stock Exchange', 'BMV', (SELECT id FROM public.countries WHERE iso_code = 'MX'), 'America/Mexico_City',
        NOW()),
       ('Oslo Stock Exchange', 'OSE', (SELECT id FROM public.countries WHERE iso_code = 'NO'), 'Europe/Oslo', NOW()),
       ('Stockholm Stock Exchange', 'OMXSTO', (SELECT id FROM public.countries WHERE iso_code = 'SE'),
        'Europe/Stockholm',
        NOW()), -- Unique code
       ('Copenhagen Stock Exchange', 'OMXCPH', (SELECT id FROM public.countries WHERE iso_code = 'DK'),
        'Europe/Copenhagen',
        NOW()), -- Unique code
       ('Helsinki Stock Exchange', 'OMXHEL', (SELECT id FROM public.countries WHERE iso_code = 'FI'), 'Europe/Helsinki',
        NOW()), -- Unique code
       ('Warsaw Stock Exchange', 'WSE', (SELECT id FROM public.countries WHERE iso_code = 'PL'), 'Europe/Warsaw',
        NOW()),
       ('Athens Stock Exchange', 'ATHEX', (SELECT id FROM public.countries WHERE iso_code = 'GR'), 'Europe/Athens',
        NOW()),
       ('Istanbul Stock Exchange', 'BIST', (SELECT id FROM public.countries WHERE iso_code = 'TR'), 'Europe/Istanbul',
        NOW()),
       ('Tel Aviv Stock Exchange', 'TASE', (SELECT id FROM public.countries WHERE iso_code = 'IL'), 'Asia/Jerusalem',
        NOW()),
       ('New Zealand Exchange', 'NZX', (SELECT id FROM public.countries WHERE iso_code = 'NZ'), 'Pacific/Auckland',
        NOW());