INSERT INTO sectors (name, description, created_at)
VALUES ('Energy',
        'Companies engaged in the exploration, production, and refining of energy resources such as oil, gas, and coal.',
        now()),
       ('Materials',
        'Companies involved in the production of raw materials, including chemicals, metals, and construction materials.',
        now()),
       ('Industrials',
        'Companies that manufacture and distribute capital goods, provide commercial services, and operate in transportation and infrastructure.',
        now()),
       ('Consumer Discretionary',
        'Companies that provide non-essential goods and services, such as retail, automotive, and leisure products.',
        now()),
       ('Consumer Staples',
        'Companies that produce essential goods and services, such as food, beverages, and household products.', now()),
       ('Health Care',
        'Companies involved in health care services, pharmaceuticals, biotechnology, and medical devices.', now()),
       ('Financials', 'Companies that provide financial services, including banks, insurance, and investment firms.',
        now()),
       ('Information Technology',
        'Companies that develop and provide technology products and services, including software, hardware, and IT services.',
        now()),
       ('Communication Services',
        'Companies that provide communication and media services, including telecommunications, internet, and entertainment.',
        now()),
       ('Utilities', 'Companies that provide essential utilities such as electricity, gas, and water.', now()),
       ('Real Estate',
        'Companies that own, operate, and invest in real estate properties, including REITs (Real Estate Investment Trusts).',
        now());